<!DOCTYPE HTML PUBLIC "html.dtd">
<html>
<HEAD>
<TITLE>
Link Grammar Miscellaneous Publications Mirror
</TITLE>
</HEAD>
<BODY BGCOLOR="ffffff">
<H1>Mirrors of Miscellaneous Publications</H1>


    <table class="sortable">
      <thead>
        <tr>
          <th>Filename</th>
          <th>Size <small>(bytes)</small></th>
        </tr>
      </thead>
      <tbody>

      <?
        $myDirectory=opendir(".");
        
        while($name=readdir($myDirectory)) {

          // Don't print . and .. and other hidden files
          if($name[0]!="." && $name!="index.phtml") {
              $size=number_format(filesize($name));
              print("
              <tr>
                <td><a href='./$name'>$name</a></td>
                <td>&nbsp;&nbsp;$size</td>
              </tr>");
            }
        }
        
        // Closes directory
        closedir($myDirectory);
      ?>
      </tbody>
    </table>
  
</body>
</html>
